- hosts: vm1
  become: yes
  tasks: 
  - name: Install apache 
    ansible.builtin.apt:
      name: unzip
      state: absent 
      update_cache: yes
    notify: 
      - Create user brad
      - Restart service apache

  handlers:
  - name: Restart service apache
    ansible.builtin.service:
      name: apache2
      state: restarted

  - name: Create user brad
    ansible.builtin.user:
      name: brad